CKEDITOR.dialog.add("syntaxhighlightDialog",function(b){var e=function(a){a={};a.hideGutter=b.config.syntaxhighlight_hideGutter;a.hideControls=b.config.syntaxhighlight_hideControls;a.collapse=b.config.syntaxhighlight_collapse;a.showColumns=b.config.syntaxhighlight_showColumns;a.noWrap=b.config.syntaxhighlight_noWrap;a.firstLineChecked=b.config.syntaxhighlight_firstLineChecked;a.firstLine=b.config.syntaxhighlight_firstLine;a.highlightChecked=b.config.syntaxhighlight_highlightChecked;a.highlight=b.config.syntaxhighlight_highlight;
a.lang=b.config.syntaxhighlight_lang;a.code=b.config.syntaxhighlight_code;return a};return{title:b.lang.syntaxhighlight.title,minWidth:500,minHeight:400,contents:[{id:"source",label:b.lang.syntaxhighlight.sourceTab,accessKey:"S",elements:[{type:"vbox",children:[{id:"cmbLang",type:"select",labelLayout:"horizontal",label:b.lang.syntaxhighlight.langLbl,widths:["25%","75%"],items:[["ActionScript3","as3"],["AppleScript","applescript"],["Bash (Shell)","bash"],["ColdFusion","cf"],["C#","csharp"],["C++",
"cpp"],["CSS","css"],["Delphi","delphi"],["Diff","diff"],["Erlang","erl"],["Groovy","groovy"],["Haxe","hx"],["Javascript","jscript"],["Java","java"],["Java FX","javafx"],["Perl","perl"],["PHP","php"],["Plain (Text)","plain"],["PowerShell","ps"],["Python","python"],["Ruby","ruby"],["Sass","scss"],["Scala","scala"],["SQL","sql"],["VB","vb"],["XML/XHTML","xml"]],setup:function(a){a.lang&&this.setValue(a.lang)},commit:function(a){a.lang=this.getValue()}}]},{type:"textarea",id:"hl_code",rows:22,style:"width:100%",
validate:CKEDITOR.dialog.validate.notEmpty(b.lang.syntaxhighlight.sourceTextareaEmptyError),setup:function(a){a.code&&this.setValue(a.code)},commit:function(a){a.code=this.getValue()}}]},{id:"advanced",label:b.lang.syntaxhighlight.advancedTab,accessKey:"A",elements:[{type:"vbox",children:[{type:"html",html:"<strong>"+b.lang.syntaxhighlight.hideGutter+"</strong>"},{type:"checkbox",id:"hide_gutter",label:b.lang.syntaxhighlight.hideGutterLbl,setup:function(a){this.setValue(a.hideGutter)},commit:function(a){a.hideGutter=
this.getValue()}},{type:"html",html:"<strong>"+b.lang.syntaxhighlight.hideControls+"</strong>"},{type:"checkbox",id:"hide_controls",label:b.lang.syntaxhighlight.hideControlsLbl,setup:function(a){this.setValue(a.hideControls)},commit:function(a){a.hideControls=this.getValue()}},{type:"html",html:"<strong>"+b.lang.syntaxhighlight.collapse+"</strong>"},{type:"checkbox",id:"collapse",label:b.lang.syntaxhighlight.collapseLbl,setup:function(a){this.setValue(a.collapse)},commit:function(a){a.collapse=this.getValue()}},
{type:"html",html:"<strong>"+b.lang.syntaxhighlight.showColumns+"</strong>"},{type:"checkbox",id:"show_columns",label:b.lang.syntaxhighlight.showColumnsLbl,setup:function(a){this.setValue(a.showColumns)},commit:function(a){a.showColumns=this.getValue()}},{type:"html",html:"<strong>"+b.lang.syntaxhighlight.lineWrap+"</strong>"},{type:"checkbox",id:"line_wrap",label:b.lang.syntaxhighlight.lineWrapLbl,setup:function(a){this.setValue(a.noWrap)},commit:function(a){a.noWrap=this.getValue()}},{type:"html",
html:"<strong>"+b.lang.syntaxhighlight.lineCount+"</strong>"},{type:"hbox",widths:["5%","95%"],children:[{type:"checkbox",id:"lc_toggle",label:"",setup:function(a){this.setValue(a.firstLineChecked)},commit:function(a){a.firstLineChecked=this.getValue()}},{type:"text",id:"default_lc",style:"width:15%;",label:"",setup:function(a){1<a.firstLine&&this.setValue(a.firstLine)},commit:function(a){this.getValue()&&""!=this.getValue()&&(a.firstLine=this.getValue())}}]},{type:"html",html:"<strong>"+b.lang.syntaxhighlight.highlight+
"</strong>"},{type:"hbox",widths:["5%","95%"],children:[{type:"checkbox",id:"hl_toggle",label:"",setup:function(a){this.setValue(a.highlightChecked)},commit:function(a){a.highlightChecked=this.getValue()}},{type:"text",id:"default_hl",style:"width:40%;",label:"",setup:function(a){null!=a.highlight&&this.setValue(a.highlight)},commit:function(a){this.getValue()&&""!=this.getValue()&&(a.highlight=this.getValue())}}]},{type:"hbox",widths:["5%","95%"],children:[{type:"html",html:""},{type:"html",html:"<i>"+
b.lang.syntaxhighlight.highlightLbl+"</i>"}]}]}]}],onShow:function(){var a=this.getParentEditor().getSelection().getStartElement(),a=a&&a.getAscendant("pre",!0),c=null;if(a){c=a.getHtml();c=c.replace(/<br>/g,"\n");c=c.replace(/&amp;/g,"&");c=c.replace(/&lt;/g,"<");c=c.replace(/&gt;/g,">");code=c=c.replace(/&quot;/g,'"');a=a.getAttribute("class");c=e();if(a){if(-1<a.indexOf("brush")){var b=/brush:[ ]{0,1}(\w*)/.exec(a);null!=b&&0<b.length&&(c.lang=b[1].replace(/^\s+|\s+$/g,""))}-1<a.indexOf("gutter")&&
(c.hideGutter=!0);-1<a.indexOf("toolbar")&&(c.hideControls=!0);-1<a.indexOf("collapse")&&(c.collapse=!0);-1<a.indexOf("first-line")&&(b=/first-line:[ ]{0,1}([0-9]{1,4})/.exec(a),null!=b&&(0<b.length&&1<b[1])&&(c.firstLineChecked=!0,c.firstLine=b[1]));-1<a.indexOf("highlight")&&a.match(/highlight:[ ]{0,1}\[[0-9]+(,[0-9]+)*\]/)&&(b=/highlight:[ ]{0,1}\[(.*)\]/.exec(a),null!=b&&0<b.length&&(c.highlightChecked=!0,c.highlight=b[1]));-1<a.indexOf("ruler")&&(c.showColumns=!0);-1<a.indexOf("wrap-lines")&&
(c.noWrap=!0)}c.code=code}else c=e();this.setupContent(c)},onOk:function(){var a=this.getParentEditor(),c=a.getSelection().getStartElement(),b=c&&c.getAscendant("pre",!0),c=e();this.commitContent(c);var d;d="brush:"+c.lang+";";c.hideGutter&&(d+="gutter:false;");c.hideControls&&(d+="toolbar:false;");c.collapse&&(d+="collapse:true;");c.showColumns&&(d+="ruler:true;");c.noWrap&&(d+="wrap-lines:false;");c.firstLineChecked&&1<c.firstLine&&(d+="first-line:"+c.firstLine+";");c.highlightChecked&&""!=c.highlight&&
(d+="highlight: ["+c.highlight.replace(/\s/gi,"")+"];");b?(b.setAttribute("class",d),b.setText(c.code)):(b=new CKEDITOR.dom.element("pre"),b.setAttribute("class",d),b.setText(c.code),a.insertElement(b))}}});